Rename st-version: --> collection:, add auxillary files to archive

diff --git a/releng/mk-release-archive-test b/releng/mk-release-archive-test
--- a/releng/mk-release-archive-test
+++ b/releng/mk-release-archive-test
@@ -33,17 +33,21 @@ git init foo-project
 )
 
 {
-    echo st-version: test-v0.1
+    echo collection: test-v0.1
     echo component: file://$(realpath foo-project) v0.1 $(cd foo-project && git show -s --format='tformat:%H' HEAD)
 } > foo-manifest
 
-../mk-release-archive.sh foo-manifest
+echo "New stuff" > NEWS
 
-tar -tzf st-test-v0.1.tar.gz | grep -q '^st-test-v0.1/foo-project/README' || die "FAIL: README file missing in archive"
+../mk-release-archive.sh foo-manifest NEWS
 
-! ../mk-release-archive.sh -o st-expect-fail -a /dev/null foo-manifest || die "FAIL: Signatures not enforced"
+tar -tzf test-v0.1.tar.gz | grep -q '^test-v0.1/foo-project/README' || die "FAIL: README file missing in archive"
+tar -tzf test-v0.1.tar.gz | grep -q '^test-v0.1/manifest' || die "FAIL: manifest file missing in archive"
+tar -tzf test-v0.1.tar.gz | grep -q '^test-v0.1/NEWS' || die "FAIL: NEWS file missing in archive"
+
+! ../mk-release-archive.sh -o test-expect-fail -a /dev/null foo-manifest || die "FAIL: Signatures not enforced"
 
 # Test with -f, and also test passing an absolute filename with -o.
-../mk-release-archive.sh -f -o "$(pwd)/st-unsigned" -a /dev/null foo-manifest || die "FAIL: -f (force) not working"
+../mk-release-archive.sh -f -o "$(pwd)/test-unsigned" -a /dev/null foo-manifest || die "FAIL: -f (force) not working"
 
-tar -tzf st-unsigned.tar.gz | grep -q '^st-unsigned/foo-project/README' || die "FAIL: README file missing in (forced) archive"
+tar -tzf test-unsigned.tar.gz | grep -q '^test-unsigned/foo-project/README' || die "FAIL: README file missing in (forced) archive"
